### ISSUE TITLE
Panic on Mac OSX M1 

### ISSUE THREAD

**Issue by leonardinius** [nabaz-io/nabaz#14]
**Describe the bug**

M1 MacOsx go tests panic! 

**To Reproduce**

```
cd $(mktemp -d)
go install github.com/nabaz-io/nabaz/cmd/nabaz@latest
git clone https://github.com/leonardinius/smtpd-proxy.git
cd smtpd-proxy
nabaz hypertest --cmdline "go test ./..."
```

**Expected behavior**
Working tests

**Screenshots**

```
 running tests (first run, running the entire test suite)...
panic: runtime error: index out of range [1] with length 1

goroutine 23 [running]:
github.com/nabaz-io/nabaz/pkg/hypertest/framework.(*GoTest).getCoverageData(0x140002426e0)
/Users/leo/go/pkg/mod/github.com/nabaz-io/nabaz@v0.0.0-20221116155107-08b0bee0aa2c/pkg/hypertest/framework/gotest.go:318 +0x7cc
github.com/nabaz-io/nabaz/pkg/hypertest/framework.(*GoTest).RunTests(0x140002426e0, 0x1400012ca80)
/Users/leo/go/pkg/mod/github.com/nabaz-io/nabaz@v0.0.0-20221116155107-08b0bee0aa2c/pkg/hypertest/framework/gotest.go:286 +0xc38
github.com/nabaz-io/nabaz/pkg/hypertest.Run({0x16b7e7982, 0xd}, {0x14000200c60, 0x1c}, {0x104e15500, 0x14000205350}, 0x1400025e6c0?)
/Users/leo/go/pkg/mod/github.com/nabaz-io/nabaz@v0.0.0-20221116155107-08b0bee0aa2c/pkg/hypertest/run.go:109 +0x2d8
github.com/nabaz-io/nabaz/pkg/hypertest.runNabazWhenNeeded({0x16b7e7982, 0xd}, {0x14000200c60, 0x1c}, {0x104e15500, 0x14000205350}, 0x0?, 0x0?)
/Users/leo/go/pkg/mod/github.com/nabaz-io/nabaz@v0.0.0-20221116155107-08b0bee0aa2c/pkg/hypertest/run.go:408 +0x1c4
created by github.com/nabaz-io/nabaz/pkg/hypertest.Execute
/Users/leo/go/pkg/mod/github.com/nabaz-io/nabaz@v0.0.0-20221116155107-08b0bee0aa2c/pkg/hypertest/run.go:441 +0x2b4
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Mac OS 13.01 ventura 
 - M1 Air

**Additional context**

**Comment by yuvalsteuer** [comment]
Thanks for sharing! 

Missed a dependency:

```
mkdir -p $GOPATH/github.com/nabaz-io
cd $GOPATH/github.com/nabaz-io
git clone https://github.com/nabaz-io/go
cd go/src/github.com/nabaz-io
./make.bash
mv $GOPATH/src/github.com/nabaz-io/go /usr/local/nabaz-go
```

**Comment by bbrks** [comment]
I'm seeing the same crash on a non-M1 mac - and that's _with_ `nabaz-go` installed as specified above

```
> nabaz hypertest --cmdline "go test ./..."
Let's increase kern.maxfilesperproc
Password:
🧠 thinking...
🚀 running tests (first run, running the entire test suite)...
panic: runtime error: index out of range [1] with length 1

goroutine 5 [running]:
github.com/nabaz-io/nabaz/pkg/hypertest/framework.(*GoTest).getCoverageData(0xc0000cc960)
	/Users/benbrooks/dev/go/pkg/mod/github.com/nabaz-io/nabaz@v0.0.0-20221116211153-e8df80c9d79c/pkg/hypertest/framework/gotest.go:318 +0x9b2
github.com/nabaz-io/nabaz/pkg/hypertest/framework.(*GoTest).RunTests(0xc0000cc960, 0xc00068f9b0)
	/Users/benbrooks/dev/go/pkg/mod/github.com/nabaz-io/nabaz@v0.0.0-20221116211153-e8df80c9d79c/pkg/hypertest/framework/gotest.go:286 +0xfc5
github.com/nabaz-io/nabaz/pkg/hypertest.Run({0x7ff7bfeff992, 0xd}, {0xc0000301e0, 0x24}, {0x10084d040, 0xc000200390}, 0xc000038360?)
	/Users/benbrooks/dev/go/pkg/mod/github.com/nabaz-io/nabaz@v0.0.0-20221116211153-e8df80c9d79c/pkg/hypertest/run.go:109 +0x448
github.com/nabaz-io/nabaz/pkg/hypertest.runNabazWhenNeeded({0x7ff7bfeff992, 0xd}, {0xc0000301e0, 0x24}, {0x10084d040, 0xc000200390}, 0x0?, 0x0?)
	/Users/benbrooks/dev/go/pkg/mod/github.com/nabaz-io/nabaz@v0.0.0-20221116211153-e8df80c9d79c/pkg/hypertest/run.go:408 +0x265
created by github.com/nabaz-io/nabaz/pkg/hypertest.Execute
	/Users/benbrooks/dev/go/pkg/mod/github.com/nabaz-io/nabaz@v0.0.0-20221116211153-e8df80c9d79c/pkg/hypertest/run.go:441 +0x38f
```

**Comment by bbrks** [comment]
I think maybe `/usr/local/nabaz-go` refers to the entire go source tree (including ./bin after compilation) - I'll try rebuilding and doing that instead

**Comment by bbrks** [comment]
Ok - once I'd unpicked several mistakes (differing `$GOPATH` and missing `src` directory), and moving the entire tree, it does finally seem to be running. Thanks for the pointers!

**Comment by yuvalsteuer** [comment]
Fixed README.md!

Send a working snap and I'll close the issue?

**Comment by bbrks** [comment]
Kinda working anyway... :) Not sure what to do from here yet but it's obvious that it's running my test packages now.

![Screenshot 2022-11-17 at 16 13 39](https://user-images.githubusercontent.com/1525809/202498912-a7511db7-22a4-4e43-bdb8-ff021ed8b3ce.png)

**Comment by yuvalsteuer** [comment]
> Kinda working anyway... :) Not sure what to do from here yet but it's obvious that it's running my test packages now. It takes several minutes to fail with this error.
> 
> ![Screenshot 2022-11-17 at 16 13 39](https://user-images.githubusercontent.com/1525809/202498912-a7511db7-22a4-4e43-bdb8-ff021ed8b3ce.png)
> 
> For context: I'm in a Go module project, in `package main` and in the root (where `go.mod` is) - underneath it are several packages full of tests.

do you have .git inside root? currently root is where .git is.

**Comment by bbrks** [comment]
Yeah, I do have a full git repo initialised there.
Is there anything else I can do to diagnose, like more verbose logging or something?

```
> ls -la
drwxr-xr-x    - benbrooks 17 Nov 18:30 .git/
drwxr-xr-x    - benbrooks 17 Nov 14:16 .github/
.rw-r--r--  185 benbrooks 17 Nov 14:16 .gitignore
.rw-r--r-- 5.9k benbrooks 17 Nov 14:16 .golangci-strict.yml
.rw-r--r-- 4.3k benbrooks 17 Nov 14:16 .golangci.yml
drwxr-xr-x    - benbrooks 17 Nov 14:46 .idea/
.rw-r--r-- 1.1k benbrooks 17 Nov 14:16 .redocly.yaml
drwxr-xr-x    - benbrooks 17 Nov 14:18 auth/
drwxr-xr-x    - benbrooks 17 Nov 14:18 base/
.rwxr-xr-x  774 benbrooks 17 Nov 14:16 bench.sh*
.rwxr-xr-x 6.3k benbrooks 17 Nov 14:16 bootstrap.sh*
drwxr-xr-x    - benbrooks 17 Nov 14:16 build/
.rwxr-xr-x 2.3k benbrooks 17 Nov 14:16 build.sh*
drwxr-xr-x    - benbrooks 17 Nov 14:16 channels/
.rw-r--r-- 3.1k benbrooks 17 Nov 14:16 CONTRIBUTING.md
drwxr-xr-x    - benbrooks 17 Nov 14:18 db/
.rw-r--r-- 1.5k benbrooks 17 Nov 14:16 Dockerfile
drwxr-xr-x    - benbrooks 17 Nov 14:16 docs/
drwxr-xr-x    - benbrooks 17 Nov 14:16 examples/
.rw-r--r-- 3.6k benbrooks 17 Nov 14:16 go.mod
.rw-r--r--  62k benbrooks 17 Nov 14:16 go.sum
.rwxr-xr-x 8.5k benbrooks 17 Nov 14:16 jenkins-integration-build.sh*
.rw-r--r--  24k benbrooks 17 Nov 14:16 Jenkinsfile
.rw-r--r--  319 benbrooks 17 Nov 14:16 LICENSE
drwxr-xr-x    - benbrooks 17 Nov 14:16 licenses/
.rw-r--r--  609 benbrooks 17 Nov 14:16 main.go
.rw-r--r--  113 benbrooks 17 Nov 14:16 Makefile
drwxr-xr-x    - benbrooks 17 Nov 14:18 manifest/
.rw-r--r-- 2.6k benbrooks 17 Nov 14:16 README.md
drwxr-xr-x    - benbrooks 17 Nov 14:46 rest/
.rw-r--r-- 3.2k benbrooks 17 Nov 14:16 rewrite-manifest.sh
drwxr-xr-x    - benbrooks 17 Nov 14:16 service/
.rwxr-xr-x 1.4k benbrooks 17 Nov 14:16 set-version-stamp.sh*
.rwxr-xr-x 4.4k benbrooks 17 Nov 14:16 snap-manifest.sh*
.rwxr-xr-x  37M benbrooks 17 Nov 14:17 a.out*
.rwxr-xr-x 3.8k benbrooks 17 Nov 14:16 test-integration-init.sh*
.rwxr-xr-x 2.2k benbrooks 17 Nov 14:16 test.sh*
.rwxr-xr-x 2.0k benbrooks 17 Nov 14:16 test_with_coverage.sh*
drwxr-xr-x    - benbrooks 17 Nov 14:16 tools/
> git status
On branch CBG-2420
Your branch is up to date with 'origin/CBG-2420'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   rest/config.go
	modified:   rest/serverless_test.go

no changes added to commit (use "git add" and/or "git commit -a")
> git remote -v
origin	git@github.com:couchbase/sync_gateway.git (fetch)
origin	git@github.com:couchbase/sync_gateway.git (push)
```

**Comment by yuvalsteuer** [comment]
reproduction steps, I'll step in, somethings weird.

```
git clone git@github.com:couchbase/sync_gateway.git 
cd sync_gateway
go mod tidy
nabaz hypertest --cmdline "go test ./..."
```

is that it?

**Comment by bbrks** [comment]
Basically yes - although the repo was not a fresh clone so maybe there's something weird going on in there, or with pre-existing Go caches. I can always clean up and try again.

Really looking forward to trying this project out, as I think it'd help me out a lot.

**Comment by yuvalsteuer** [comment]
Figured out the problem, working on a fix. 🤝

**Comment by yuvalsteuer** [comment]
@bbrks
Remove **/tmp/nabaz.db** if exists, and pull main branch!
Should work now. 

https://github.com/nabaz-io/nabaz/commit/c8cb4cbb4328eeca4b392bdff8313a7f8580b1da#diff-fb39d95e14992e31041386ead19916cbb6c078df688140b707c4cff3fcd35686

**Comment by yuvalsteuer** [comment]
Waiting for ✅ from you @bbrks

**Comment by bbrks** [comment]
Sorry I'm busy with work atm.

Will give this another go when I get a spare moment.
